/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLMyComponentElement extends HTMLStencilElement {
    'first': string;
    'last': string;
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}


declare global {
  interface HTMLZoAmbassadorCardElement extends HTMLStencilElement {
    'activity': string;
    'bgalt': string;
    'bgimage': string;
    'name': string;
    'pagelink': string;
  }
  var HTMLZoAmbassadorCardElement: {
    prototype: HTMLZoAmbassadorCardElement;
    new (): HTMLZoAmbassadorCardElement;
  };
  interface HTMLElementTagNameMap {
    'zo-ambassador-card': HTMLZoAmbassadorCardElement;
  }
  interface ElementTagNameMap {
    'zo-ambassador-card': HTMLZoAmbassadorCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'zo-ambassador-card': JSXElements.ZoAmbassadorCardAttributes;
    }
  }
  namespace JSXElements {
    export interface ZoAmbassadorCardAttributes extends HTMLAttributes {
      'activity'?: string;
      'bgalt'?: string;
      'bgimage'?: string;
      'name'?: string;
      'pagelink'?: string;
    }
  }
}


declare global {
  interface HTMLZoIconElement extends HTMLStencilElement {
    'thing': string;
  }
  var HTMLZoIconElement: {
    prototype: HTMLZoIconElement;
    new (): HTMLZoIconElement;
  };
  interface HTMLElementTagNameMap {
    'zo-icon': HTMLZoIconElement;
  }
  interface ElementTagNameMap {
    'zo-icon': HTMLZoIconElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'zo-icon': JSXElements.ZoIconAttributes;
    }
  }
  namespace JSXElements {
    export interface ZoIconAttributes extends HTMLAttributes {
      'thing'?: string;
    }
  }
}


declare global {
  interface HTMLZoPromoBarElement extends HTMLStencilElement {
    'message': string;
  }
  var HTMLZoPromoBarElement: {
    prototype: HTMLZoPromoBarElement;
    new (): HTMLZoPromoBarElement;
  };
  interface HTMLElementTagNameMap {
    'zo-promo-bar': HTMLZoPromoBarElement;
  }
  interface ElementTagNameMap {
    'zo-promo-bar': HTMLZoPromoBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'zo-promo-bar': JSXElements.ZoPromoBarAttributes;
    }
  }
  namespace JSXElements {
    export interface ZoPromoBarAttributes extends HTMLAttributes {
      'message'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
